# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateField(max_length=250),
        ),
    ]
