# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20170422_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='genre',
            field=models.CharField(choices=[('RO', 'Rock'), ('HH', 'Hip Hop'), ('POP', 'Pop'), ('EDM', 'Electronic'), ('NA', 'N/A')], default='NA', max_length=3),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateTimeField(max_length=250),
        ),
    ]
